# Generated by Django 3.0.4 on 2020-06-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255, verbose_name='书籍')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('fenlei', models.CharField(max_length=255, verbose_name='分类')),
                ('content', models.TextField(verbose_name='内容')),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': '书籍',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='font.Telephone')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
